/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pruebas;

import java.awt.Color;

/**
 *
 * @author AlmacenPC
 */
public class Rectificado extends javax.swing.JInternalFrame {

    /**
     * Creates new form Rectificado
     */
    public Rectificado() {
        initComponents();
        ((javax.swing.plaf.basic.BasicInternalFrameUI) this.getUI()).setNorthPane(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla1 = new ColorRojo();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        btnSalir = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        cmbEnviar = new javax.swing.JComboBox<>();
        btnPausa = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();

        setBorder(null);
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new java.awt.BorderLayout(20, 20));

        Tabla1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Tabla1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "PRIORIDAD", "NUMERO DE PLANO", "PROYECTO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Tabla1.setFocusable(false);
        Tabla1.setRowHeight(25);
        Tabla1.setSelectionBackground(new java.awt.Color(110, 201, 255));
        Tabla1.setShowHorizontalLines(true);
        Tabla1.getTableHeader().setReorderingAllowed(false);
        Tabla1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Tabla1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Tabla1MouseEntered(evt);
            }
        });
        jScrollPane1.setViewportView(Tabla1);

        jPanel1.add(jScrollPane1, java.awt.BorderLayout.LINE_START);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(0, 165, 252));

        jLabel10.setFont(new java.awt.Font("Roboto Light", 1, 60)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("       RECTIFICADO       ");
        jPanel3.add(jLabel10);

        jPanel2.add(jPanel3);

        btnSalir.setBackground(new java.awt.Color(255, 255, 255));

        jLabel9.setFont(new java.awt.Font("Roboto", 0, 36)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("X");
        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel9MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel9MouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnSalirLayout = new javax.swing.GroupLayout(btnSalir);
        btnSalir.setLayout(btnSalirLayout);
        btnSalirLayout.setHorizontalGroup(
            btnSalirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnSalirLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        btnSalirLayout.setVerticalGroup(
            btnSalirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnSalirLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel2.add(btnSalir);

        jPanel1.add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new java.awt.GridLayout(1, 3));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(new javax.swing.BoxLayout(jPanel5, javax.swing.BoxLayout.Y_AXIS));

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel1.setText("DATOS DEL PLANO");
        jPanel5.add(jLabel1);

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("A");
        jPanel5.add(jLabel5);

        jLabel3.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel3.setText("NUMERO DE EMPLEADO");
        jPanel5.add(jLabel3);

        jTextField1.setBackground(new java.awt.Color(255, 255, 255));
        jTextField1.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jTextField1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        jPanel5.add(jTextField1);

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("A");
        jPanel5.add(jLabel6);

        jLabel11.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel11.setText("CODIGO DE BARRAS");
        jPanel5.add(jLabel11);

        jTextField2.setBackground(new java.awt.Color(255, 255, 255));
        jTextField2.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jTextField2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        jPanel5.add(jTextField2);

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("A");
        jPanel5.add(jLabel7);

        jLabel2.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel2.setText("NUMERO DE PLANO");
        jPanel5.add(jLabel2);

        jTextField3.setBackground(new java.awt.Color(255, 255, 255));
        jTextField3.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jTextField3.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        jPanel5.add(jTextField3);

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("A");
        jPanel5.add(jLabel8);

        jLabel4.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel4.setText("HORA DE INICIO");
        jPanel5.add(jLabel4);

        jTextField4.setBackground(new java.awt.Color(255, 255, 255));
        jTextField4.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jTextField4.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        jPanel5.add(jTextField4);

        jPanel4.add(jPanel5);

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setLayout(new java.awt.GridLayout(3, 0));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.add(jPanel6);

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setLayout(new java.awt.GridLayout(4, 0, 10, 15));

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));

        cmbEnviar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONAR", "ACABADOS", "FRESADORA", "TORNO", "CORTES" }));
        cmbEnviar.setPreferredSize(new java.awt.Dimension(170, 30));
        jPanel10.add(cmbEnviar);

        jPanel9.add(jPanel10);

        btnPausa.setBackground(new java.awt.Color(255, 255, 255));
        btnPausa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/pausa.png"))); // NOI18N
        btnPausa.setBorder(null);
        btnPausa.setContentAreaFilled(false);
        btnPausa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPausa.setFocusPainted(false);
        btnPausa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPausaActionPerformed(evt);
            }
        });
        jPanel9.add(btnPausa);

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/actualizar (1).png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setFocusPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel9.add(jButton1);

        btnGuardar.setBackground(new java.awt.Color(255, 255, 255));
        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/enviar (1).png"))); // NOI18N
        btnGuardar.setBorder(null);
        btnGuardar.setContentAreaFilled(false);
        btnGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGuardar.setFocusPainted(false);
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jPanel9.add(btnGuardar);

        jPanel8.add(jPanel9);

        jPanel4.add(jPanel8);

        jPanel1.add(jPanel4, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Tabla1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tabla1MouseClicked
//        int fila = Tabla1.getSelectedRow();
//        try{
//            char comillas = '"';
//            Runtime.getRuntime().exec("cmd /c start \\\\100.100.200.10\\bd\\OC\\PDF_Planos\\"+comillas+Tabla1.getValueAt(fila, 2)+comillas+"\\"+comillas+Tabla1.getValueAt(fila, 1)+".pdf"+comillas);
//
//            }catch(IOException  e){
//                JOptionPane.showMessageDialog(this, "PDF NO ENCONTRADO");
//            }
    }//GEN-LAST:event_Tabla1MouseClicked

    private void Tabla1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tabla1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_Tabla1MouseEntered

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
//        limpiarTabla();
//        verDatos();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnPausaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPausaActionPerformed
////        Date fecha = new Date();
////        SimpleDateFormat fec1 = new SimpleDateFormat ("dd/MM/yyyy HH:mm:ss");
////        String fec = fec1.format(fecha);
////        String f = "";
////        try{
////            Connection con = null;
////            Conexion con1 = new Conexion();
////            con = con1.getConnection();
////            Statement st = con.createStatement();
////            String sql = "UPDATE CNC SET Proyecto = ?, Plano = ?, FechaInicio = ?, FechaFinal = ?, Terminado = ?, Estado = ?, Cronometro = ?, Prioridad = ? WHERE Proyecto = ?";
////            String ver = "select * from CNC where Proyecto like '"+txtProyecto.getText()+"'";
////            PreparedStatement pst = con.prepareStatement(sql);
////            ResultSet rs = st.executeQuery(ver);
////            String datos[] = new String[10];
////            while(rs.next()){
////                datos[1] = rs.getString("Proyecto");
////                datos[2] = rs.getString("Plano");
////                datos[3] = rs.getString("FechaInicio");
////                datos[4] = rs.getString("FechaFinal");
////                datos[5] = rs.getString("Terminado");
////                datos[6] = rs.getString("Estado");
////                datos[7] = rs.getString("Cronometro");
////                datos[8] = rs.getString("Prioridad");
////            }
////            if(datos[1] != null){
////
////                if(datos[7] != null){
////                    String fecha1 = txtFecha.getText();
////                    String fecha2 = fec;
////
////                    int hora1,hora2,minuto1,minuto2;
////                    int fecha9 = 0,fecha10 = 0;
////                    String f1,f2,f4,f5,fin = "";
////
////                    f1 = fecha1.substring(11,13);
////                    f2 = fecha1.substring(14,16);
////                    f4 = fecha2.substring(11,13);
////                    f5 = fecha2.substring(14,16);
////
////                    hora1 = Integer.parseInt(f1);
////                    minuto1 = Integer.parseInt(f2);
////                    hora2= Integer.parseInt(f4);
////                    minuto2 = Integer.parseInt(f5);
////
////                    fecha9 = (hora2 - hora1);
////                    if(hora2 >= hora1 && minuto2 >= minuto1){
////                        if((fecha9) < 10 && (minuto2 - minuto2) < 10){
////                            fin = "0"+(fecha9)+":"+"0"+(minuto2-minuto1);
////                        }else if((fecha9) < 10){
////                            fin = "0"+(fecha9)+":"+(minuto2-minuto1);
////                        }else if((minuto2 - minuto1) < 10){
////                            fin = (fecha9)+":"+"0"+(minuto2-minuto1);
////                        }
////
////                    }else{
////                        if(minuto2 < minuto1){
////                            fecha10 = (60 - minuto1) + minuto2;
////                            fecha9 = fecha9-1;
////                            if(fecha9 < 10 && (fecha10) < 10){
////                                fin = "0"+fecha9+":"+"0"+fecha10;
////                            }else if((fecha9) < 10){
////                                fin = "0"+(fecha9)+":"+(fecha10);
////                            }else if((fecha10) < 10){
////                                fin = (fecha9)+":"+"0"+(fecha10);
////                            }
////                        }else if(minuto2 > minuto1){
////                            fecha10 = (minuto2 - minuto1);
////                            if(fecha9 < 10 && (fecha10) < 10){
////                                fin = "0"+fecha9+":"+"0"+fecha10;
////                            }else if((fecha9) < 10){
////                                fin = "0"+(fecha9)+":"+(fecha10);
////                            }else if((fecha10) < 10){
////                                fin = (fecha9)+":"+"0"+(fecha10);
////                            }
////                        }
////                    }
////                    String a = datos[7].substring(0,2);
////                    String b = datos[7].substring(3,5);
////                    String c = fin.substring(0,2);
////                    String d = fin.substring(3,5);
////
////                    int h1,m1,h2,m2;
////                    h1 = Integer.parseInt(a);
////                    m1 = Integer.parseInt(b);
////                    h2 = Integer.parseInt(c);
////                    m2 = Integer.parseInt(d);
////
////                    int sumaH,sumaM;
////                    sumaH = h1+h2;
////                    sumaM = m1+m2;
////
////                    if(sumaM >= 60){
////                        sumaM = (sumaM - 60);
////                        sumaH = sumaH + 1;
////                    }
////
////                    if((sumaH) < 10 && (sumaM) < 10){
////                        f = "0"+(sumaH)+":"+"0"+(sumaM);
////                    }else if((sumaH) < 10){
////                        f = "0"+(sumaH)+":"+(sumaM);
////                    } else if((sumaM) < 10){
////                        f = (sumaH)+":"+"0"+(sumaM);
////                    }
////                }
////                pst.setString(1, txtProyecto.getText());
////                pst.setString(2, datos[2]);
////                pst.setString(3, "");
////                pst.setString(4, "");
////                pst.setString(5, datos[5]);
////                pst.setString(6, datos[6]);
////                pst.setString(7, f);
////                pst.setString(8, datos[8]);
////                pst.setString(9, txtProyecto.getText());
////
////                int n = pst.executeUpdate();
////
////                if(n > 0){
////                    limpiarTabla();
////                    verDatos();
////                    estado = false;
////                    txtFecha.setText("");
////                    txtProyecto.setText("");
////                    JOptionPane.showMessageDialog(this, "PLANO PAUSADO","INFORME",JOptionPane.INFORMATION_MESSAGE);
////                }
////            }
////        }catch(SQLException e){
////            JOptionPane.showMessageDialog(this, "ERROR AL PAUSAR "+e,"ERROR",JOptionPane.ERROR_MESSAGE);
////        }
    }//GEN-LAST:event_btnPausaActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
//        Date fecha = new Date();
//        int fila = Tabla1.getSelectedRow();
//        SimpleDateFormat fec1 = new SimpleDateFormat ("dd/MM/yyyy HH:mm:ss");
//        String fec = fec1.format(fecha);
//        if(txtNumero.getText().equals("")){
//            JOptionPane.showMessageDialog(this, "DEBES LLENAR EL NUMERO DE EMPLEADO","ERROR",JOptionPane.ERROR_MESSAGE);
//        }else if(txtProyecto.getText().equals("")){
//            JOptionPane.showMessageDialog(this, "DEBES SELECCIONAR UN PROYECTO","ERROR",JOptionPane.ERROR_MESSAGE);
//        }else{
//            try{
//                Connection con = null;
//                Conexion con1 = new Conexion();
//                con = con1.getConnection();
//                estado = false;
//                Statement st = con.createStatement();
//                Statement st1 = con.createStatement();
//                Statement st2 = con.createStatement();
//                Statement st3 = con.createStatement();
//                Statement st4 = con.createStatement();
//                String sql =  "UPDATE CNC SET Proyecto = ?, Plano = ?, FechaInicio = ?, FechaFinal = ?, Terminado = ?, Estado = ?, Cronometro = ?, Prioridad = ?, Empleado = ? WHERE Proyecto = ?";
//                String sql1 = "insert into Fresadora (Proyecto,Plano,FechaInicio,FechaFinal,Terminado,Estado,Cronometro,Prioridad) values(?,?,?,?,?,?,?,?)";
//                String sql2 = "insert into Datos (Proyecto,Plano,FechaInicio,FechaFinal,Terminado, Estado,Cronometro,Prioridad) values(?,?,?,?,?,?,?,?)";
//                String sql4 = "insert into Torno (Proyecto,Plano,FechaInicio,FechaFinal,Terminado, Estado,Cronometro,Prioridad) values(?,?,?,?,?,?,?,?)";
//                String sql5 = "insert into Acabados (Proyecto,Plano,FechaInicio,FechaFinal,Terminado, Estado,Cronometro,Prioridad) values(?,?,?,?,?,?,?,?)";
//                PreparedStatement pst = con.prepareStatement(sql);
//                PreparedStatement pst1 = con.prepareStatement(sql1);
//                PreparedStatement pst2 = con.prepareStatement(sql2);
//                PreparedStatement pst4 = con.prepareStatement(sql4);
//                PreparedStatement pst5 = con.prepareStatement(sql5);
//
//                String ver = "select * from Fresadora where Proyecto like '"+txtProyecto.getText()+"'";
//                String ver1 = "select * from Datos where Proyecto like '"+txtProyecto.getText()+"'";
//                String ver2 = "select * from Torno where Proyecto like '"+txtProyecto.getText()+"'";
//                String ver3 = "select * from Acabados where Proyecto like '"+txtProyecto.getText()+"'";
//
//                ResultSet rs = st.executeQuery(ver);
//                ResultSet rs1 = st1.executeQuery(ver1);
//                ResultSet rs2 = st2.executeQuery(ver2);
//                ResultSet rs3 = st3.executeQuery(ver3);
//
//                String ac = "update Fresadora set Proyecto = ?, Plano = ?, FechaInicio = ?, FechaFinal = ?, Terminado = ?, Estado = ?, Cronometro = ?, Prioridad = ? where Proyecto = ?";
//                String ac1 = "update Datos set Proyecto = ?, Plano = ?, FechaInicio = ?, FechaFinal = ?, Terminado = ?, Estado = ?, Cronometro = ?, Prioridad = ? where Proyecto = ?";
//                String ac2 = "update Torno set Proyecto = ?, Plano = ?, FechaInicio = ?, FechaFinal = ?, Terminado = ?, Estado = ?, Cronometro = ?, Prioridad = ? where Proyecto = ?";
//                String ac3 = "update Acabados set Proyecto = ?, Plano = ?, FechaInicio = ?, FechaFinal = ?, Terminado = ?, Estado = ?, Cronometro = ?, Prioridad = ? where Proyecto = ?";
//                PreparedStatement act = con.prepareStatement(ac);
//                PreparedStatement act1 = con.prepareStatement(ac1);
//                PreparedStatement act2 = con.prepareStatement(ac2);
//                PreparedStatement act3 = con.prepareStatement(ac3);
//
//                String ecnc = "select * from CNC where Proyecto like '"+txtProyecto.getText()+"'";
//                ResultSet eC = st4.executeQuery(ecnc);
//                String fresa[] = new String[10];
//                String acabados[] = new String[10];
//                String torno[] = new String[10];
//                String cnc[] = new String[10];
//                String cortes[] = new String[10];
//                while(eC.next()){
//                    cnc[1] = eC.getString("Estado");
//                    cnc[2] = eC.getString("FechaInicio");
//                    cnc[3] = eC.getString("FechaFinal");
//                    cnc[4] = eC.getString("Cronometro");
//                    cnc[5] = eC.getString("Plano");
//                    cnc[6] = eC.getString("Prioridad");
//                    cnc[7] = eC.getString("Empleado");
//                }
//                while(rs.next()){
//                    fresa[1] = rs.getString("Proyecto");
//                    fresa[2] = rs.getString("Estado");
//                    fresa[3] = rs.getString("Cronometro");
//                }
//                while(rs3.next()){
//                    acabados[1] = rs3.getString("Proyecto");
//                    acabados[3] = rs3.getString("Cronometro");
//                }
//                while(rs2.next()){
//                    torno[1] = rs2.getString("Proyecto");
//                    torno[3] = rs2.getString("Cronometro");
//                }
//                while(rs1.next()){
//                    cortes[1] = rs1.getString("Proyecto");
//                    cortes[3] = rs1.getString("Cronometro");
//                }
//
//                if(cnc[4] != "00:00"){
//                    String fecha1 = txtFecha.getText();
//                    String fecha2 = fec;
//
//                    int hora1,hora2,minuto1,minuto2;
//                    int fecha9 = 0,fecha10 = 0;
//                    String f1,f2,f4,f5,fin = "";
//
//                    f1 = fecha1.substring(11,13);
//                    f2 = fecha1.substring(14,16);
//                    f4 = fecha2.substring(11,13);
//                    f5 = fecha2.substring(14,16);
//
//                    hora1 = Integer.parseInt(f1);
//                    minuto1 = Integer.parseInt(f2);
//                    hora2= Integer.parseInt(f4);
//                    minuto2 = Integer.parseInt(f5);
//
//                    fecha9 = (hora2 - hora1);
//                    if(hora2 >= hora1 && minuto2 >= minuto1){
//                        if((fecha9) < 10 && (minuto2 - minuto2) < 10){
//                            fin = "0"+(fecha9)+":"+"0"+(minuto2-minuto1);
//                        }else if((fecha9) < 10){
//                            fin = "0"+(fecha9)+":"+(minuto2-minuto1);
//                        }else if((minuto2 - minuto1) < 10){
//                            fin = (fecha9)+":"+"0"+(minuto2-minuto1);
//                        }
//
//                    }else{
//                        if(minuto2 < minuto1){
//                            fecha10 = (60 - minuto1) + minuto2;
//                            fecha9 = fecha9-1;
//                            if(fecha9 < 10 && (fecha10) < 10){
//                                fin = "0"+fecha9+":"+"0"+fecha10;
//                            }else if((fecha9) < 10){
//                                fin = "0"+(fecha9)+":"+(fecha10);
//                            }else if((fecha10) < 10){
//                                fin = (fecha9)+":"+"0"+(fecha10);
//                            }
//                        }else if(minuto2 > minuto1){
//                            fecha10 = (minuto2 - minuto1);
//                            if(fecha9 < 10 && (fecha10) < 10){
//                                fin = "0"+fecha9+":"+"0"+fecha10;
//                            }else if((fecha9) < 10){
//                                fin = "0"+(fecha9)+":"+(fecha10);
//                            }else if((fecha10) < 10){
//                                fin = (fecha9)+":"+"0"+(fecha10);
//                            }
//                        }
//                    }
//                    String a = cnc[4].substring(0,2);
//                    String b = cnc[4].substring(3,5);
//                    String c = fin.substring(0,2);
//                    String d = fin.substring(3,5);
//
//                    int h1,m1,h2,m2;
//                    String f = "";
//                    h1 = Integer.parseInt(a);
//                    m1 = Integer.parseInt(b);
//                    h2 = Integer.parseInt(c);
//                    m2 = Integer.parseInt(d);
//
//                    int sumaH,sumaM;
//                    sumaH = h1+h2;
//                    sumaM = m1+m2;
//
//                    if(sumaM >= 60){
//                        sumaM = (sumaM - 60);
//                        sumaH = sumaH + 1;
//                    }
//
//                    if((sumaH) < 10 && (sumaM) < 10){
//                        f = "0"+(sumaH)+":"+"0"+(sumaM);
//                    }else if((sumaH) < 10){
//                        f = "0"+(sumaH)+":"+(sumaM);
//                    } else if((sumaM) < 10){
//                        f = (sumaH)+":"+"0"+(sumaM);
//                    }
//                    String as;
//                    if(cnc[7] == null || cnc[7].equals("")){
//                        as = txtNumero.getText();
//                    }else{
//                        as = cnc[7]+","+txtNumero.getText();
//                    }
//                    pst.setString(1, txtProyecto.getText());
//                    pst.setString(2, cnc[5]);
//                    pst.setString(3, txtFecha.getText());
//                    pst.setString(4, fec);
//                    pst.setString(5, "SI");
//                    pst.setString(6, cnc[1]);
//                    pst.setString(7, f);
//                    pst.setString(8, cnc[6]);
//                    pst.setString(9, as);
//                    pst.setString(10, txtProyecto.getText());
//
//                }else{
//                    String as = null;
//                    if(cnc[7] == null || cnc[7].equals("")){
//                        as = txtNumero.getText();
//                    }else{
//                        as = cnc[7]+","+txtNumero.getText();
//                    }
//                    pst.setString(1, txtProyecto.getText());
//                    pst.setString(2, cnc[5]);
//                    pst.setString(3, txtFecha.getText());
//                    pst.setString(4, fec);
//                    pst.setString(5, "SI");
//                    pst.setString(6, cnc[1]);
//                    pst.setString(7, cronometro(txtFecha.getText(),fec));
//                    pst.setString(8, cnc[6]);
//                    pst.setString(9, as);
//                    pst.setString(10, txtProyecto.getText());
//                }
//
//                if(cmbEnviar.getSelectedIndex() == 0){
//                    JOptionPane.showMessageDialog(this, "DEBE ESCOGER UNA OPCION","",JOptionPane.ERROR_MESSAGE);
//                }else
//                if(cmbEnviar.getSelectedIndex() == 1)
//                {
//                    if(acabados[1] == (null)){
//                        pst5.setString(1, txtProyecto.getText());
//                        pst5.setString(2, cnc[5]);
//                        pst5.setString(3, "");
//                        pst5.setString(4, "");
//                        pst5.setString(5, "NO");
//                        pst5.setString(6, cnc[1]);
//                        pst5.setString(7, "00:00");
//                        pst5.setString(8, cnc[6]);
//                        int n = pst5.executeUpdate();
//                        int n1 = pst.executeUpdate();
//                        if (n1 > 0 && n > 0 )
//                        {
//                            tabla();
//                            borrar();
//                        }
//                    }else{
//                        act3.setString(1, txtProyecto.getText());
//                        act3.setString(2, cnc[5]);
//                        act3.setString(3, "");
//                        act3.setString(4, "");
//                        act3.setString(5, "NO");
//                        act3.setString(6, cnc[1]);
//                        act3.setString(7, acabados[3]);
//                        act3.setString(8, cnc[6]);
//                        act3.setString(9, txtProyecto.getText());
//                        int n = act3.executeUpdate();
//                        int n1 = pst.executeUpdate();
//                        if (n > 0 && n1 >0){
//                            tabla();
//                            borrar();
//                        }
//
//                    }
//                }
//                else if(cmbEnviar.getSelectedIndex() == 2){
//                    if(fresa[1] == (null)){
//                        pst1.setString(1, txtProyecto.getText());
//                        pst1.setString(2, cnc[5]);
//                        pst1.setString(3, "");
//                        pst1.setString(4, "");
//                        pst1.setString(5, "NO");
//                        pst1.setString(6, cnc[1]);
//                        pst1.setString(7, "00:00");
//                        pst1.setString(8, cnc[6]);
//                        int n = pst1.executeUpdate();
//                        int n1 = pst.executeUpdate();
//                        if (n > 0 && n1 > 0)
//                        {
//                            tabla();
//                            borrar();
//                        }
//                    }else{
//                        act.setString(1, txtProyecto.getText());
//                        act.setString(2, cnc[5]);
//                        act.setString(3, "");
//                        act.setString(4, "");
//                        act.setString(5, "NO");
//                        act.setString(6, cnc[1]);
//                        act.setString(7, torno[3]);
//                        act.setString(8, cnc[6]);
//                        act.setString(9, txtProyecto.getText());
//                        int n = act.executeUpdate();
//                        int n1 = pst.executeUpdate();
//                        if (n1 > 0 && n > 0){
//                            tabla();
//                            borrar();
//                        }                    }
//
//                    }else if(cmbEnviar.getSelectedIndex() == 3){
//                        if(torno[1] == (null)){
//                            pst4.setString(1, txtProyecto.getText());
//                            pst4.setString(2, cnc[5]);
//                            pst4.setString(3, "");
//                            pst4.setString(4, "");
//                            pst4.setString(5, "NO");
//                            pst4.setString(6, cnc[1]);
//                            pst4.setString(7, "00:00");
//                            pst4.setString(8, cnc[6]);
//                            int n = pst4.executeUpdate();
//                            int n1 = pst.executeUpdate();
//                            if (n1 > 0 && n > 0)
//                            {
//                                tabla();
//                                borrar();
//                            }
//                        }else{
//                            act2.setString(1, txtProyecto.getText());
//                            act2.setString(2, cnc[5]);
//                            act2.setString(3, "");
//                            act2.setString(4, "");
//                            act2.setString(5, "NO");
//                            act2.setString(6, cnc[1]);
//                            act2.setString(7, torno[3]);
//                            act2.setString(8, cnc[6]);
//                            act2.setString(9, txtProyecto.getText());
//                            int n = act2.executeUpdate();
//                            int n1 = pst.executeUpdate();
//                            if (n1 > 0 && n > 0){
//                                tabla();
//                                borrar();
//                            }
//                        }
//                    }else if(cmbEnviar.getSelectedIndex() == 4){
//                        if(cortes[1] == (null)){
//                            pst2.setString(1, txtProyecto.getText());
//                            pst2.setString(2, cnc[5]);
//                            pst2.setString(3, "");
//                            pst2.setString(4, "");
//                            pst2.setString(5, "NO");
//                            pst2.setString(6, cnc[1]);
//                            pst2.setString(7, "00:00");
//                            pst2.setString(8, cnc[6]);
//                            int n = pst2.executeUpdate();
//                            int n1 = pst.executeUpdate();
//                            if (n1 > 0 && n > 0)
//                            {
//                                tabla();
//                                borrar();
//                            }
//                        }else{
//                            act1.setString(1, txtProyecto.getText());
//                            act1.setString(2, cnc[5]);
//                            act1.setString(3, "");
//                            act1.setString(4, "");
//                            act1.setString(5, "NO");
//                            act1.setString(6, cnc[1]);
//                            act1.setString(7, cortes[3]);
//                            act1.setString(8, cnc[6]);
//                            act1.setString(9, txtProyecto.getText());
//                            int n = act1.executeUpdate();
//                            int n1 = pst.executeUpdate();
//                            if (n1 > 0 && n > 0){
//                                tabla();
//                                borrar();
//                            }
//                        }
//                    }
//
//                }catch(SQLException e){
//
//                    JOptionPane.showMessageDialog(null, "NO SE PUEDE ENVIAR INFORMACION"+e,"ERROR",JOptionPane.ERROR_MESSAGE);
//                }
//        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        dispose();
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabel9MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseEntered
        btnSalir.setBackground(Color.red);
    }//GEN-LAST:event_jLabel9MouseEntered

    private void jLabel9MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseExited
        btnSalir.setBackground(Color.white);
    }//GEN-LAST:event_jLabel9MouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tabla1;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnPausa;
    private javax.swing.JPanel btnSalir;
    private javax.swing.JComboBox<String> cmbEnviar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
