/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package VentanaEmergente.CambiarEstado;

import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.util.ArrayList;
import pruebas.CambiarEstado;

/**
 *
 * @author jaleman
 */
public class FiltrarPlanos extends javax.swing.JFrame {

    /**
     * Creates new form FiltrarPlanos
     */
    private CambiarEstado ventanaPadre;

    public FiltrarPlanos(CambiarEstado ventanaPadre) {
        initComponents();
        this.ventanaPadre = ventanaPadre;
        setLocationRelativeTo(null);
        chkTodosPlanos.addItemListener(new ItemListener() {
                @Override
                public void itemStateChanged(ItemEvent e) {
                    boolean seleccionado = (e.getStateChange() == ItemEvent.SELECTED);
                    chkAcabados.setEnabled(!seleccionado);
                    chkCortes.setEnabled(!seleccionado);
                    chkMaquinados.setEnabled(!seleccionado);
                    chkCalidad.setEnabled(!seleccionado);
                    chkTerminadoCalidad.setEnabled(!seleccionado);
                    chkSinMaterial.setEnabled(!seleccionado);
                    if (seleccionado) {
                        chkAcabados.setEnabled(false);
                        chkCortes.setEnabled(false);
                        chkMaquinados.setEnabled(false);
                        chkCalidad.setEnabled(false);
                        chkTerminadoCalidad.setEnabled(false);
                        chkSinMaterial.setEnabled(false);
                    }
                }
            });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        chkTodosPlanos = new javax.swing.JCheckBox();
        chkMaquinados = new javax.swing.JCheckBox();
        chkTerminadoCalidad = new javax.swing.JCheckBox();
        chkCalidad = new javax.swing.JCheckBox();
        chkCortes = new javax.swing.JCheckBox();
        chkAcabados = new javax.swing.JCheckBox();
        chkSinMaterial = new javax.swing.JCheckBox();
        jPanel2 = new javax.swing.JPanel();
        btnAceptarFiltros = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.Y_AXIS));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new java.awt.GridLayout(9, 0));

        jLabel12.setFont(new java.awt.Font("Lexend", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 165, 252));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("SELECCIONA EL ESTADO A FILTRAR");
        jPanel1.add(jLabel12);

        chkTodosPlanos.setText("TODOS LOS PLANOS");
        jPanel1.add(chkTodosPlanos);

        chkMaquinados.setText("MAQUINADOS");
        jPanel1.add(chkMaquinados);

        chkTerminadoCalidad.setText("TERMINADO (CALIDAD)");
        jPanel1.add(chkTerminadoCalidad);

        chkCalidad.setText("CALIDAD");
        jPanel1.add(chkCalidad);

        chkCortes.setText("CORTES");
        jPanel1.add(chkCortes);

        chkAcabados.setText("ACABADOS");
        jPanel1.add(chkAcabados);

        chkSinMaterial.setText("SIN MATERIAL");
        jPanel1.add(chkSinMaterial);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        btnAceptarFiltros.setText("Filtrar");
        btnAceptarFiltros.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAceptarFiltros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarFiltrosActionPerformed(evt);
            }
        });
        jPanel2.add(btnAceptarFiltros);

        jPanel1.add(jPanel2);

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAceptarFiltrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarFiltrosActionPerformed
        ArrayList<String> estados = new ArrayList<>();

        if (chkTodosPlanos.isSelected()) {
            estados.add("TODOS");
        } else {

            if (chkAcabados.isSelected()) {
                estados.add("ACABADOS");
            }

            if (chkCortes.isSelected()) {
                estados.add("CORTES");
            }

            if (chkMaquinados.isSelected()) {
                estados.add("MAQUINADOS");
            }

            if (chkCalidad.isSelected()) {
                estados.add("CALIDAD");
            }

            if (chkTerminadoCalidad.isSelected()) {
                estados.add("TERMINADO (CALIDAD)");
            }

            if (chkSinMaterial.isSelected()) {
                estados.add("SIN MATERIAL");
            }
        }

        ventanaPadre.cargarPlanosFiltrados(estados);

        dispose();
    }//GEN-LAST:event_btnAceptarFiltrosActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptarFiltros;
    private javax.swing.JCheckBox chkAcabados;
    private javax.swing.JCheckBox chkCalidad;
    private javax.swing.JCheckBox chkCortes;
    private javax.swing.JCheckBox chkMaquinados;
    private javax.swing.JCheckBox chkSinMaterial;
    private javax.swing.JCheckBox chkTerminadoCalidad;
    private javax.swing.JCheckBox chkTodosPlanos;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
